// lib\models\log_aktivitas_model.dart
class LogAktivitasModel {
  final int logId;
  final int userId;
  final String aktivitas;
  final String? tabelTerkait;
  final int? idTerkait;
  final String? deskripsi;
  final String? userAgent;
  final DateTime? createdAt;
  
  // Relational data (optional)
  final UserModel? user;

  LogAktivitasModel({
    required this.logId,
    required this.userId,
    required this.aktivitas,
    this.tabelTerkait,
    this.idTerkait,
    this.deskripsi,
    this.userAgent,
    this.createdAt,
    this.user,
  });

  // Factory constructor untuk membuat instance dari JSON
  factory LogAktivitasModel.fromJson(Map<String, dynamic> json) {
    return LogAktivitasModel(
      logId: json['log_id'] as int,
      userId: json['user_id'] as int,
      aktivitas: json['aktivitas'] as String,
      tabelTerkait: json['tabel_terkait'] as String?,
      idTerkait: json['id_terkait'] as int?,
      deskripsi: json['deskripsi'] as String?,
      userAgent: json['user_agent'] as String?,
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : null,
      user: json['user'] != null
          ? UserModel.fromJson(json['user'] as Map<String, dynamic>)
          : null,
    );
  }

  // Method untuk convert instance ke JSON
  Map<String, dynamic> toJson() {
    return {
      'log_id': logId,
      'user_id': userId,
      'aktivitas': aktivitas,
      'tabel_terkait': tabelTerkait,
      'id_terkait': idTerkait,
      'deskripsi': deskripsi,
      'user_agent': userAgent,
      'created_at': createdAt?.toIso8601String(),
    };
  }

  // Method untuk insert (tanpa log_id, created_at)
  Map<String, dynamic> toInsertJson() {
    return {
      'user_id': userId,
      'aktivitas': aktivitas,
      'tabel_terkait': tabelTerkait,
      'id_terkait': idTerkait,
      'deskripsi': deskripsi,
      'user_agent': userAgent,
    };
  }

  // CopyWith method untuk immutability
  LogAktivitasModel copyWith({
    int? logId,
    int? userId,
    String? aktivitas,
    String? tabelTerkait,
    int? idTerkait,
    String? deskripsi,
    String? userAgent,
    DateTime? createdAt,
    UserModel? user,
  }) {
    return LogAktivitasModel(
      logId: logId ?? this.logId,
      userId: userId ?? this.userId,
      aktivitas: aktivitas ?? this.aktivitas,
      tabelTerkait: tabelTerkait ?? this.tabelTerkait,
      idTerkait: idTerkait ?? this.idTerkait,
      deskripsi: deskripsi ?? this.deskripsi,
      userAgent: userAgent ?? this.userAgent,
      createdAt: createdAt ?? this.createdAt,
      user: user ?? this.user,
    );
  }

  // Helper method untuk membuat log aktivitas
  static LogAktivitasModel create({
    required int userId,
    required String aktivitas,
    String? tabelTerkait,
    int? idTerkait,
    String? deskripsi,
    String? userAgent,
  }) {
    return LogAktivitasModel(
      logId: 0, // Will be generated by database
      userId: userId,
      aktivitas: aktivitas,
      tabelTerkait: tabelTerkait,
      idTerkait: idTerkait,
      deskripsi: deskripsi,
      userAgent: userAgent,
    );
  }

  // Helper methods untuk jenis aktivitas
  bool get isLogin => aktivitas.toLowerCase().contains('login');
  bool get isLogout => aktivitas.toLowerCase().contains('logout');
  bool get isCreate => aktivitas.toLowerCase().contains('create') || 
                       aktivitas.toLowerCase().contains('tambah');
  bool get isUpdate => aktivitas.toLowerCase().contains('update') || 
                       aktivitas.toLowerCase().contains('ubah');
  bool get isDelete => aktivitas.toLowerCase().contains('delete') || 
                       aktivitas.toLowerCase().contains('hapus');
  bool get isApproval => aktivitas.toLowerCase().contains('approve') || 
                         aktivitas.toLowerCase().contains('setujui');
}

// Import UserModel untuk relasi
class UserModel {
  final int userId;
  final String username;
  final String namaLengkap;
  final String email;

  UserModel({
    required this.userId,
    required this.username,
    required this.namaLengkap,
    required this.email,
  });

  factory UserModel.fromJson(Map<String, dynamic> json) {
    return UserModel(
      userId: json['user_id'] as int,
      username: json['username'] as String,
      namaLengkap: json['nama_lengkap'] as String,
      email: json['email'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'user_id': userId,
      'username': username,
      'nama_lengkap': namaLengkap,
      'email': email,
    };
  }
}